export default [
  {
    id: 1,
    description: 'A robot head with an unusually large eye and teloscpic neck -- excellent for exploring high spaces.',
    name: 'Large Cyclops',
    imageUrl: new URL('./images/head-big-eye.png', import.meta.url).href,
    category: 'Heads',
    price: 1220.5,
    discount: 0.2,
  },
  {
    id: 17,
    description: 'A spring base - great for reaching high places.',
    name: 'Spring Base',
    imageUrl: new URL('./images/base-spring.png', import.meta.url).href,
    category: 'Bases',
    price: 1190.5,
    discount: 0,
  },
  {
    id: 6,
    description: 'An articulated arm with a claw -- great for reaching around corners or working in tight spaces.',
    name: 'Articulated Arm',
    imageUrl: new URL('./images/arm-articulated-claw.png', import.meta.url).href,
    category: 'Arms',
    price: 275,
    discount: 0,
  },
  {
    id: 2,
    description: 'A friendly robot head with two eyes and a smile -- great for domestic use.',
    name: 'Friendly Bot',
    imageUrl: new URL('./images/head-friendly.png', import.meta.url).href,
    category: 'Heads',
    price: 945.0,
    discount: 0.3,
  },
  {
    id: 3,
    description: 'A large three-eyed head with a shredder for a mouth -- great for crushing light medals or shredding documents.',
    name: 'Shredder',
    imageUrl: new URL('./images/head-shredder.png', import.meta.url).href,
    category: 'Heads',
    price: 1275.5,
    discount: 0,
  },
  {
    id: 16,
    description: 'A single-wheeled base with an accelerometer capable of higher speeds and navigating rougher terrain than the two-wheeled variety.',
    name: 'Single Wheeled Base',
    imageUrl: new URL('./images/base-single-wheel.png', import.meta.url).href,
    category: 'Bases',
    price: 1190.5,
    discount: 0.1,
  },
  {
    id: 13,
    description: 'A simple torso with a pouch for carrying items.',
    name: 'Pouch Torso',
    imageUrl: new URL('./images/torso-pouch.png', import.meta.url).href,
    category: 'Torsos',
    price: 785,
    discount: 0,
  },
  {
    id: 7,
    description: 'An arm with two independent claws -- great when you need an extra hand. Need four hands? Equip your bot with two of these arms.',
    name: 'Two Clawed Arm',
    imageUrl: new URL('./images/arm-dual-claw.png', import.meta.url).href,
    category: 'Arms',
    price: 285,
    discount: 0,
  },
  {
    id: 4,
    description: 'A simple single-eyed head -- simple and inexpensive.',
    name: 'Small Cyclops',
    imageUrl: new URL('./images/head-single-eye.png', import.meta.url).href,
    category: 'Heads',
    price: 750.0,
    discount: 0,
  },
  {
    id: 9,
    description: 'An arm with a propeller -- good for propulsion or as a cooling fan.',
    name: 'Propeller Arm',
    imageUrl: new URL('./images/arm-propeller.png', import.meta.url).href,
    category: 'Arms',
    price: 230,
    discount: 0.1,
  },
  {
    id: 15,
    description: 'A rocket base capable of high speed, controlled flight.',
    name: 'Rocket Base',
    imageUrl: new URL('./images/base-rocket.png', import.meta.url).href,
    category: 'Bases',
    price: 1520.5,
    discount: 0,
  },
  {
    id: 10,
    description: 'A short and stubby arm with a claw -- simple, but cheap.',
    name: 'Stubby Claw Arm',
    imageUrl: new URL('./images/arm-stubby-claw.png', import.meta.url).href,
    category: 'Arms',
    price: 125,
    discount: 0,
  },
  {
    id: 11,
    description: 'A torso that can bend slightly at the waist and equiped with a heat guage.',
    name: 'Flexible Gauged Torso',
    imageUrl: new URL('./images/torso-flexible-gauged.png', import.meta.url).href,
    category: 'Torsos',
    price: 1575,
    discount: 0,
  },
  {
    id: 14,
    description: 'A two wheeled base with an accelerometer for stability.',
    name: 'Double Wheeled Base',
    imageUrl: new URL('./images/base-double-wheel.png', import.meta.url).href,
    category: 'Bases',
    price: 895,
    discount: 0,
  },
  {
    id: 5,
    description: 'A robot head with three oscillating eyes -- excellent for surveillance.',
    name: 'Surveillance',
    imageUrl: new URL('./images/head-surveillance.png', import.meta.url).href,
    category: 'Heads',
    price: 1255.5,
    discount: 0,
  },
  {
    id: 8,
    description: 'A telescoping arm with a grabber.',
    name: 'Grabber Arm',
    imageUrl: new URL('./images/arm-grabber.png', import.meta.url).href,
    category: 'Arms',
    price: 205.5,
    discount: 0,
  },
  {
    id: 12,
    description: 'A less flexible torso with a battery gauge.',
    name: 'Gauged Torso',
    imageUrl: new URL('./images/torso-gauged.png', import.meta.url).href,
    category: 'Torsos',
    price: 1385,
    discount: 0,
  },
  {
    id: 18,
    description: 'An inexpensive three-wheeled base. only capable of slow speeds and can only function on smooth surfaces.',
    name: 'Triple Wheeled Base',
    imageUrl: new URL('./images/base-triple-wheel.png', import.meta.url).href,
    category: 'Bases',
    price: 700.5,
    discount: 0,
  },
]